name: check-links

on:
  push:
    branches:
      - "iss-152"
#  schedule:
#    - cron: '15 17 * * 1'

jobs:
  check-links:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:

      - name: Checkout the lesson
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: 'oldrel'

      - name: Install needed packages
        run: |
          install.packages(c('rvest', 'purr', 'dplyr', 'httr'))
        shell: Rscript {0}

      - name: Check URL links
        run: |
          source("bin/detect-broken-links.R")
          detect_broken_links("https://umcarpentries.org/intro-curriculum-r/00-intro/index.html")
        shell: Rscript {0}
